
select * from cities;
select * from countries;
select * from crop_insurance;
select * from emp_temp;
select * from employee;
select * from employees;
select * from mytable;
select * from sales_order_info;
select * from student_info;
select * from tutorials;

--Countries List
CREATE TABLE countries(
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_name VARCHAR2(100) NOT NULL,
    alpha2 char(2),
    alpha3 char(3),
    country_code NUMBER(10,0),
    region VARCHAR2(100),
    sub_region VARCHAR2(100),
    intermediate_region VARCHAR2(100),
    region_code NUMBER(10,0),
    sub_region_code NUMBER(10,0),
    intermediate_region_code NUMBER(10,0),
    CONSTRAINT country_id_PK PRIMARY KEY(country_id)
);

create table countries_bkp as select * from countries;

--=============Sales Order Data=======================================
CREATE TABLE sales_order_info(
    sales_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Region VARCHAR2(50) NOT NULL,
    Country VARCHAR2(50) NOT NULL,
	Item_Type varchar2(50),
	Sales_Channel varchar2(50),
	Order_Priority char(1),
	Order_Date timestamp,
	Order_ID number(20,0),
	Ship_Date timestamp,
	Units_Sold number,
	Unit_Price number(20,5),
	Unit_Cost number(20,5),
	Total_Revenue number(20,5),
	Total_Cost number(20,5),
	Total_Profit number(20,5),
    CONSTRAINT sales_id_PK PRIMARY KEY(sales_id)
);

--Order_Date,Ship_Date  while importing DD-MM-YYYY HH.MI.SS.ff7 AM

--=====================Student Info Start=========================================
CREATE TABLE student_info(
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR2(50) NOT NULL,
    father_name VARCHAR2(50) NOT NULL,
	gender varchar2(10),
	MOBILE long,
	CATEGORY varchar2(20),
    CONSTRAINT student_id_PK PRIMARY KEY(student_id)
);

select * from student_info where
(upper(GENDER)='FEMALE' and CATEGORY not in ('SC','ST') OR upper(GENDER)='MALE' and CATEGORY not in ('OC','BC-C','BC-D','SC'));

--===============Student Info End==============================================

--====================Crop Insurance=================
CREATE TABLE crop_insurance(
    serial_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    mandal_name VARCHAR2(100) ,
    village_name VARCHAR2(100) ,
	Name_of_the_Beneficiary VARCHAR2(100) ,
    Crop VARCHAR2(100) ,
	Extent_Ha  number,
    Claim_Amount_Rs  int,
    Category_Loanee_Non_Loanee VARCHAR2(10) ,
    Bank_Name  VARCHAR2(100) ,
    Branch_Name  VARCHAR2(100) ,
    Account_Number number,
    CONSTRAINT serial_no_PK PRIMARY KEY(serial_no)
);

--=======================================================
  CREATE TABLE "EMPLOYEES"
    (	Emp_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
 	"FIRST_NAME" VARCHAR2(50 CHAR),
     LAST_NAME VARCHAR2(50 CHAR),
     "COMPANY_NAME" VARCHAR2(100 CHAR),
 	"ADDRESS" VARCHAR2(100 CHAR),
 	"CITY" VARCHAR2(100 CHAR),
 	"COUNTRY" VARCHAR2(100 CHAR),
 	"ZIP" NUMBER,
     "EMP_STATE" VARCHAR2(100 CHAR),
 	 CONSTRAINT "EMP_ID_PK" PRIMARY KEY ("EMP_ID")
    );

--=======================================================

CREATE TABLE cities(id INT, name VARCHAR(255), population INT);

INSERT INTO cities(id,name, population) VALUES(1,'Bratislava', 432000);
INSERT INTO cities(id,name, population) VALUES(2,'Budapest', 1759000);
INSERT INTO cities(id,name, population) VALUES(3,'Prague', 1280000);
INSERT INTO cities(id,name, population) VALUES(4,'Warsaw', 1748000);
INSERT INTO cities(id,name, population) VALUES(5,'Los Angeles', 3971000);
INSERT INTO cities(id,name, population) VALUES(6,'New York', 8550000);
INSERT INTO cities(id,name, population) VALUES(7,'Edinburgh', 464000);
INSERT INTO cities(id,name, population) VALUES(8,'Suzhou', 4327066);
INSERT INTO cities(id,name, population) VALUES(9,'Zhengzhou', 4122087);
INSERT INTO cities(id,name, population) VALUES(10,'Berlin', 3671000);

==============================================================================
--One to many

create table LASER_SEARCH(LOOKUP_ID number,SERVICE_ID varchar2(50),constraint LOOKUP_ID_PK PRIMARY  KEY(LOOKUP_ID));
CREATE TABLE SERVICE_AUDIT (AUDIT_ID NUMBER,AUDIT_NAME VARCHAR2(50),LOOKUP_ID NUMBER,
    CONSTRAINT LOOKUP_ID_FK FOREIGN KEY (LOOKUP_ID) REFERENCES LASER_SEARCH (LOOKUP_ID),
    CONSTRAINT AUDIT_ID_PK PRIMARY KEY (AUDIT_ID)
);
CREATE TABLE CLIENT_AUDIT (CLIENT_AUDIT_ID NUMBER,CLIENT_AUDIT_NAME VARCHAR2(50),SERVICE_AUDIT_ID NUMBER,
    CONSTRAINT SERVICE_AUDIT_ID_FK FOREIGN KEY (SERVICE_AUDIT_ID) REFERENCES SERVICE_AUDIT (AUDIT_ID),
    CONSTRAINT CLIENT_AUDIT_ID_PK PRIMARY KEY (CLIENT_AUDIT_ID)
);
select * from LASER_SEARCH;
select * from SERVICE_AUDIT;
select * from CLIENT_AUDIT;

=======================================================================================
CREATE TABLE CAR(
    car_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    MANUFACTURER VARCHAR2(50) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
	TYPE varchar2(10),
    CONSTRAINT car_id_PK PRIMARY KEY(car_id)
);

=====================================================================================

CREATE TABLE EMP (EMPNO NUMBER(4) NOT NULL,ENAME VARCHAR2(10),JOB VARCHAR2(9),
MGR NUMBER(4),HIREDATE DATE,SAL NUMBER(7, 2),COMM NUMBER(7, 2),DEPTNO NUMBER(2));
INSERT INTO EMP VALUES (7369, 'SMITH', 'CLERK',    7902, TO_DATE('17-DEC-1980', 'DD-MON-YYYY'), 800, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600, 300, 30);
INSERT INTO EMP VALUES (7521, 'WARD',  'SALESMAN', 7698, TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250, 500, 30);
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER',  7839, TO_DATE('2-APR-1981',  'DD-MON-YYYY'), 2975, NULL, 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', 7698,TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP VALUES (7698, 'BLAKE', 'MANAGER', 7839,TO_DATE('1-MAY-1981', 'DD-MON-YYYY'), 2850, NULL, 30);
INSERT INTO EMP VALUES (7782, 'CLARK', 'MANAGER', 7839,TO_DATE('9-JUN-1981', 'DD-MON-YYYY'), 2450, NULL, 10);
INSERT INTO EMP VALUES (7788, 'SCOTT', 'ANALYST', 7566,TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7839, 'KING', 'PRESIDENT', NULL,TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
INSERT INTO EMP VALUES (7844, 'TURNER', 'SALESMAN', 7698,TO_DATE('8-SEP-1981', 'DD-MON-YYYY'), 1500, 0, 30);
INSERT INTO EMP VALUES (7876, 'ADAMS', 'CLERK', 7788,TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20);
INSERT INTO EMP VALUES (7900, 'JAMES', 'CLERK', 7698,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 950, NULL, 30);
INSERT INTO EMP VALUES (7902, 'FORD', 'ANALYST', 7566,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK', 7782,TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10);
==========================================================================================